-- Phase 1: authentication & user identity.

CREATE TABLE users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT users_role_check CHECK (role IN ('CUSTOMER', 'ADMIN', 'SUPPORT'))
);

CREATE TABLE customer_profiles (
    id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID         NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    first_name     VARCHAR(100),
    last_name      VARCHAR(100),
    date_of_birth  DATE,
    phone          VARCHAR(30),
    address_line1  VARCHAR(255),
    city           VARCHAR(100),
    country        VARCHAR(100),
    kyc_status     VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT customer_kyc_status_check CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED'))
);

CREATE INDEX idx_customer_profiles_kyc_status ON customer_profiles (kyc_status);

-- The demo admin account is seeded at startup by AdminSeeder (so the BCrypt hash
-- is generated by the application's PasswordEncoder).
